apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        resources:
           requests:
              memory: "128"
              cpu: "500"
           limits: 
             memory: "120mi"
             cpu:  "500"
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
