
name: K8s Linting
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install kubescore
        run: |
          wget https://github.com/zegl/kube-score/releases/download/v1.18.0/kube-score_1.18.0_linux_amd64
          chmod +x kube-score_1.18.0_linux_amd64
          mv kube-score_1.18.0_linux_amd64 kubescore

      - name: Run Kubescore
        run: |
          ./kubescore score manifests/*.yml --ignore-test pod-networkpolicy
     
      
